// pages/api/hellocoop.js
// generated by @hellocoop/quickstart --nextjs on 2025-03-25T16:24:46.096Z
// NOTE: this file should not need to be edited
import config from '../../hello.config'
import { pageAuth } from '@hellocoop/nextjs'
export default pageAuth(config)
