name: Renew Let's Encrypt Certificate

on:
  schedule:
    - cron: "0 12 10 * *" # Runs at noon on the 10th of every month
  workflow_dispatch: # Allows manual trigger for testing

jobs:
  renew-cert:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: write
      pull-requests: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      # - name: Configure AWS Credentials
      #   uses: aws-actions/configure-aws-credentials@v3
      #   with:
      #       role-to-assume: arn:aws:iam::708442275961:role/Wallet-repo
      #       aws-region: us-west-2

      # - name: Test AWS Access
      #   run: aws route53 list-hosted-zones

      # - name: Install Certbot and Dependencies
      #   run: |
      #       sudo apt-get update
      #       sudo apt-get install -y certbot python3-certbot-dns-route53

      # - name: Renew Certificate
      #   id: certbot
      #   run: |
      #       certbot certonly \
      #         --dns-route53 \
      #         --non-interactive \
      #         --agree-tos \
      #         --email contact@hello.coop \
      #         -d "*.hello-dev.net" \
      #         --server https://acme-v02.api.letsencrypt.org/directory \
      #         --config-dir ./nginx/letsencrypt \
      #         --work-dir ./nginx/letsencrypt/work \
      #         --logs-dir ./nginx/letsencrypt/logs \
      #         --force-renewal
      #   env:
      #       AWS_ACCESS_KEY_ID: ${{ env.AWS_ACCESS_KEY_ID }}
      #       AWS_SECRET_ACCESS_KEY: ${{ env.AWS_SECRET_ACCESS_KEY }}
      #       AWS_SESSION_TOKEN: ${{ env.AWS_SESSION_TOKEN }}

      # - name: Check for Certificate Renewal Failure
      #   if: failure()
      #   run: |
      #       echo "Certificate renewal failed. Exiting workflow."
      #       exit 1

      # - name: Setup github-actions bot git identity
      #   uses: qoomon/actions--setup-git@v1
      #   with:
      #     user: bot

      - name: Commit and Push Changes
        run: |
          echo "Renewal check at $(date -u)" > nginx/letsencrypt/.cert-renewal-log
        env:
          TZ: UTC # Ensures date command runs correctly in UTC

      - name: Create Pull Request
        id: create-pr
        uses: peter-evans/create-pull-request@v7
        with:
          commit-message: "Renew Let's Encrypt certificate for *.hello-dev.net"
          branch: HELLO-DEV-CERT-RENEWAL
          base: main
          title: "Renewed Certificate for hello-dev.net"
          body: "This PR updates the Let's Encrypt certificate. Please review and merge."
          labels: "certificate-renewal"
          reviewers: "rohanharikr"
          delete-branch: true
